repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: debug-statements
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix=lf"]

      - id: check-yaml
      - id: fix-encoding-pragma
        args: ["--remove"]

  - repo: https://github.com/myint/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args: [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variable",
          ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: ["--py310-plus", "--keep-runtime-typing"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
        - "--src-path=./"
        - "--line-length=120"
        - "--multi-line=VERTICAL_HANGING_INDENT"
        - "--trailing-comma"

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args:
          - "--line-length=120"
          - "--target-version=py310"
        files: '\.py$'

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [
            "flake8-blind-except",
            "flake8-commas",
            "flake8-comprehensions",
            "flake8-deprecated",
            "flake8-broken-line",
            "flake8-bugbear",
            "flake8-tidy-imports",
            "flake8-print",
            "flake8-logging-format",
            "flake8-pytest-style",
          ]
        args: [--max-line-length=120]
